### PR TITLE
Updated regex

### PR DESCRIPTION
**Pull request by Piterden**
https://repl.it/K8Ry/6
https://regex101.com/r/jPsrvR/1

```regex
(.*) === (.+?)
```

### CODE REVIEW

**Comment by alexdover** [comment]
Apologies if I am missing something, but could you explain this a bit further please?

**Comment by Piterden** [comment]
Yes
image
Explanation is in the right side.

Now it supports single and double quotes type, and checks the equivalence of quotes.

Also I need to do one little fix:

**Comment by Piterden** [comment]
Fixed value getting
image

**Comment by Piterden** [comment]
:+1:

**Pull request merged**
